# cargo-release configuration

[package]
# Don't publish to crates.io when using PR workflow
# Publishing will be handled by the release.yml workflow after tag push
publish = false

# Don't push tags in PR workflow
# Tag creation will be handled manually after PR merge
tag = false

# Don't push to git in PR workflow
# PR creation will handle the push
push = false

# Enable changelog generation
[package.metadata.release]
# Tag format
tag-name = "v{{version}}"

# Disable confirmation prompts in CI
no-dev-version = true
pre-release-commit-message = "Release {{crate_name}} v{{version}}"
pre-release-replacements = [
  { file = "CHANGELOG.md", search = "## Unreleased", replace = "## Unreleased\n\n## [{{version}}] - {{date}}", exactly = 1 },
  { file = "CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n\n## Unreleased", exactly = 1 },
]

# Don't create dev version commits in PR workflow
post-release-commit-message = false