# cargo-release configuration

# Don't publish to crates.io when using PR workflow
# Publishing will be handled by the release.yml workflow after tag push
publish = false

# Don't push tags in PR workflow
# Tag creation will be handled manually after PR merge
tag = false

# Don't push to git in PR workflow
# PR creation will handle the push
push = false

# Tag format
tag-name = "v{{version}}"

# Release commit message
pre-release-commit-message = "Release {{crate_name}} v{{version}}"