name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (patch/minor/major or specific version like 0.1.4)'
        required: true
        type: string
        default: 'patch'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release-pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install cargo-release
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-release
    
    - name: Create Release PR
      uses: cargo-bins/release-pr@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ inputs.version }}